#ifndef _UAPI_LINUX_SEG6_HMAC_H
#define _UAPI_LINUX_SEG6_HMAC_H

#define SEG6_HMAC_SECRET_LEN	64
#define SEG6_HMAC_MAX_KEY	256
#define SEG6_HMAC_FIELD_LEN	32

enum {
	SEG6_HMAC_ALGO_SHA1 = 1,
	SEG6_HMAC_ALGO_SHA256 = 2,
};

#endif
